# Equivalent to [target.thumbv7em-none-eabihf] but also disabing the runner for Miri.
[target.'cfg(all(target_arch = "arm", target_feature = "thumb2", target_feature = "v7", target_feature = "dsp", target_os = "none", target_abi = "eabihf", not(miri)))']
runner = "python3 ../cargo-runner.py"

[target.thumbv7em-none-eabihf]
linker = "./fap-lld.py"
rustflags = [
    # CPU is Cortex-M4 (STM32WB55)
    "-C",
    "target-cpu=cortex-m4",

    # Size optimizations
    "-C",
    "panic=abort",
    "-C",
    "debuginfo=0",
    "-C",
    "opt-level=z",

    # LTO helps reduce binary size
    "-C",
    "embed-bitcode=yes",
    "-C",
    "lto=yes",

    # Linker flags for relocatable binary
    "-C",
    "link-args=--script=flipperzero-rt.ld --Bstatic --relocatable --discard-all --strip-all --lto-O3 --lto-whole-program-visibility",
]

[build]
target = "thumbv7em-none-eabihf"
