name: Reusable workflow for build and test.

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.target }}
    steps:
    - uses: actions/checkout@v3.5.2
    - uses: awalsh128/cache-apt-pkgs-action@v1.3.0
      with:
        packages: libudev-dev
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        targets: x86_64-unknown-linux-gnu, thumbv7em-none-eabihf
    - name: Build
      run: cargo +nightly build --release --verbose
    - name: Build examples
      run: cargo +nightly build --examples --release --verbose
    - name: Run tests
      run: |
        cargo +nightly test --release --verbose 2>&1 | tee stderr.txt
    - name: Check that tests failed for the expected reason
      run: |
        cat stderr.txt | grep -q "Error: unable to find Flipper Zero"
